PL_Web/Models/ErrorViewModel.cs
namespace PL_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL_Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL_Web.Models;
using System.Diagnostics;

namespace PL_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL_Web/Controllers/RestauranteController.cs
using DL;
using Microsoft.AspNetCore.Mvc;

namespace PL_Web.Controllers
{
    public class RestauranteController : Controller
    {
        //10. Repetir el paso de la conexión, pero ahora referenciando a la INTERFAZ
        private readonly BL.IRestaurante _Irestaurante;
        public RestauranteController(BL.IRestaurante Irestaurante)
        {
            _Irestaurante = Irestaurante;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Restaurante restaurante = new ML.Restaurante();
            ML.Result result = _Irestaurante.GetAll(); //11. Mandar a llamar el método desde la interfaz

            if (result.Correct)
            {
                //Obtuvo toda la información
                restaurante.Restaurantes = result.Objects?.ToList();
            }
            else
            {
                restaurante.Restaurantes = new List<object>();
            }

            return View(restaurante);
        }

        [HttpGet]
        public IActionResult Form(int? idRestaurante)
        {
            ML.Restaurante restaurante = new ML.Restaurante();

            if(idRestaurante > 0)
            {
                ML.Result result = _Irestaurante.GetById(idRestaurante.Value);
                restaurante = (ML.Restaurante)result.Object;
            }

            return View(restaurante);
        }

        [HttpPost]
        public IActionResult Form(ML.Restaurante restaurante)
        {
            IFormFile file = Request.Form.Files.GetFile("inptFileImagen");

            if(file != null && file.Length > 0)
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    file.CopyTo(memoryStream);
                    restaurante.Imagen = memoryStream.ToArray();
                }
            }
            else
            {
                //Si es actualización conservar la imágen previa
                if(restaurante.IdRestaurante != 0)
                {
                    var result = _Irestaurante.GetById(restaurante.IdRestaurante);
                    if(result.Correct && result.Object != null)
                    {
                        var restauranteDB = (ML.Restaurante)result.Object;
                        restaurante.Imagen = restauranteDB.Imagen;
                    }
                }
            }

            if (restaurante.IdRestaurante == 0)
            {
                _Irestaurante.Add(restaurante);
            }
            else
            {
                _Irestaurante.Update(restaurante);
            }

            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(int idRestaurante)
        {
            _Irestaurante.Delete(idRestaurante);
            
            return RedirectToAction("GetAll");
        }
    }
}

PL_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL_Web/Views/Restaurante/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ML.Restaurante
@{
}
<h2>Agregar Restaurante</h2>
@using(Html.BeginForm("Form", "Restaurante", FormMethod.Post, new
{
    @enctype = "multipart/form-data",
    @onsubmit = "validarFormulario(event)"
}))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.IdRestaurante)
    @Html.HiddenFor(model => model.Imagen)

    <div class="card p-3 bg-light shadow-sm">
        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.Nombre, new{ @class = "form-label text-dark fw-bold"})
                @Html.TextBoxFor(model => model.Nombre, new{ @class = "form-control rounded-pill", @id = "inptNombre"})
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Eslogan, new { @class = "form-label text-dark fw-bold" })
                @Html.TextBoxFor(model => model.Eslogan, new { @class = "form-control rounded-pill", @id = "inptEslogan"})
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Descripcion, new { @class = "form-label text-dark fw-bold" })
                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control rounded-pill", @id="inptDescripcion"})
            </div>
            <div class="col">
                <label class="form-label text-dark fw-bold">Imagen del Producto</label>
                <input type="file" accept=".png" name="inptFileImagen" id="inptFileImagen" class="form-control" onchange="validarExtension(); visualizarImagen(this);" />
            </div>
        </div>
    </div>

    <p></p>
    <h3>Imagen del Restaurante</h3>
    <div class="mb-3 mt-3 col">
        @if (Model.Imagen == null)
        {
            <img id="imgRestaurante" src="https://thumb.ac-illust.com/51/51e1c1fc6f50743937e62fca9b942694_t.jpeg" width="150" height="150" />
        }
        else
        {
            <img id="imgRestaurante" src="@($"data:image/jpeg;base64,{Convert.ToBase64String(Model.Imagen)}")" width="150" height="150" />
        }
    </div>

    <div>
        <p></p>
        <button type="submit" class="btn btn-primary mb-2" name="btnAgregarRegistro" id="btnAgregarRegistro">Agregar Registro</button>
    </div>
}

<script src="~/js/ValidacionesFormulario.js"></script>

PL_Web/Views/Restaurante/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model ML.Restaurante

@{
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

<a href="@Url.Action("Form", "Restaurante")" class="btn btn-primary mb-3">
    Agregar
    <i class="bi bi-plus-square-fill"></i>
</a>

@if(Model?.Restaurantes?.Count > 0)
{
    <div class="table-responsive">
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Editar</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Eslogan</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach(ML.Restaurante restaurante in Model.Restaurantes)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Form", "Restaurante", new {IdRestaurante = restaurante.IdRestaurante})"
                               class="btn btn-warning">
                                <i class="bi bi-pencil"></i>
                            </a>
                        </td>
                        <td>@restaurante.Nombre</td>
                        <td>@restaurante.Eslogan</td>
                        <td>
                            @if (restaurante.Imagen != null)
                            {
                                <img src="@($"data:image/jpeg;base64,{Convert.ToBase64String(restaurante.Imagen)}")" width="80" height="80" />
                            }
                            else
                            {
                                <img id="imgRestaurante" src="https://thumb.ac-illust.com/51/51e1c1fc6f50743937e62fca9b942694_t.jpeg" width="80" height="80" />

                            }
                        </td>
                        <td>@restaurante.Descripcion</td>
                        <td>
                            <a href="@Url.Action("Delete", "Restaurante", new {idRestaurante = restaurante.IdRestaurante})"
                               class="btn btn-danger " onclick="return confirm('Seguro que lo quieres borrar?')">
                               <i class="bi bi-trash3"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>Pues algo salió mal</p>
}

        

PL_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurante" asp-action="GetAll">Hola</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PL_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>